# Generated by Django 6.1.1 on 2026-09-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=255)),
                ('specs', models.JSONField(blank=True, default=dict, help_text='Key-value technical specifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Industrial Equipment',
                'verbose_name_plural': 'Industrial Equipment Catalog',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('project_type', models.CharField(max_length=100)),
                ('site_sqft', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('New', 'New Inquiry'), ('Under Review', 'Under Engineering Review'), ('Contacted', 'Client Contacted'), ('Proposal Sent', 'Proposal Sent'), ('Closed', 'Closed / Won')], default='New', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client Quote / Lead',
                'verbose_name_plural': 'Client Quotes & Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Project / Client Facility Name', max_length=255)),
                ('category', models.CharField(choices=[('Fire Safety', 'Fire Safety'), ('Mechanical', 'Mechanical'), ('LPG Systems', 'LPG Systems')], db_index=True, max_length=50)),
                ('client', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('scope', models.TextField(help_text='Engineering scope of work & compliance standards')),
                ('year', models.CharField(default='2020-Present', max_length=20)),
                ('image', models.CharField(default='/images/hero.jpg', max_length=255)),
                ('featured', models.BooleanField(default=False)),
                ('highlight', models.CharField(blank=True, help_text='e.g. UL Listed Fire Pumps, NFPA 13', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mega Project',
                'verbose_name_plural': 'Mega Projects',
                'ordering': ['-id'],
            },
        ),
    ]
